### ISSUE TITLE
Support for metric-based autoscaling

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/bellhop#60]
**Is your feature request related to a problem? Please describe.**

Support for metric-based autoscaling 

**Describe alternatives you've considered**
Keep it out of score

**Additional context**
This would required Some more changes though, inspiration can be pulled from https://github.com/tomkerkhove/autoscale-aci-with-azure-serverless

**Comment by CloudViking** [comment]
Hey @tomkerkhove, 

I am going to copy your comments on this issue to Issue #9 and close this issue. We can continue this on the open discussion. 

Thanks again for all of the engagement!

**Comment by tomkerkhove** [comment]
I recall thinking to opening this bus couldn't find it, turns I did what I should have done and opened a discussion 😅

Sorry for the duplicate!
