### ISSUE TITLE
Deployment Failure -During the Action Group Creation

### ISSUE THREAD

**Issue by sumitraj0103** [Azure/bellhop#72]
**Describe the bug**
During the Current Deployment with Enable Alert. Deployment Failed

**To Reproduce**
1. Deploy  to Azure
2. Enable Email Alerting

{
    "status": "Failed",
    "error": {
        "code": "GroupShortNameIsTooLong",
        "message": "The action group short name 'testascalev2-ag' is too long. Please specify a short name with '12' or less characters"
    }
}

**Expected behavior**
Deployment  Succeed without any error

**Comment by DCMattyG** [comment]
Hey @sumitraj0103, very good catch on this! We'll get this bug fixed immediately for you sir!
