### ISSUE TITLE
Error During the Scale up:  Created Empty Tag causing issue "saveState-LicenseType"

### ISSUE THREAD

**Issue by sumitraj0103** [Azure/bellhop#76]
I found that the Auto scale down created a  saveState Tag with empty value.

TagName:   saveState-LicenseType= Empty

During the Scale up created empty tag creating problem and giving below error.
![image](https://user-images.githubusercontent.com/22010059/116843173-afdf4a80-ac11-11eb-8341-5876873cc02b.png)

**Comment by DCMattyG** [comment]
Hey @sumitraj0103, thanks for catching this! I've identified the issue and will get a fix put in place tomorrow.
